import './globals.css';
import { Poppins } from 'next/font/google';
import { LayoutWrapper } from './LayoutWrapper';
import { NoteProvider } from '@/contexts/NoteContext';

const poppins = Poppins({
  subsets: ['latin'], // Required
  weight: ['300', '400', '500', '600', '700'], // Choose needed weights
  display: 'swap', // Ensures text is visible during load
  variable: '--font-poppins', // Creates a CSS variable
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <LayoutWrapper>
          <NoteProvider>{children}</NoteProvider>
        </LayoutWrapper>
      </body>
    </html>
  );
}
